esphome:
  name: example-opentherm

esp8266:
  board: d1_mini

# Enable Home Assistant API
api:
  password: !secret ha_api_password
  encryption:
    key: !secret ha_api_encryption_key

ota:
  password: !secret ha_api_password
  on_begin:
    then:
      - lambda: |-
          ESP_LOGI("custom", "Disable Interrupts, to allow OTA without interrupts");
          InterruptLock lock;
          delay(500);

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

external_components:
#  source: github://foxey/esphome-opentherm
  source: components
  components: [opentherm]

opentherm:
  responder_read_pin: 12
  responder_write_pin: 13
  controller_read_pin: 4
  controller_write_pin: 5

sensor:
  - platform: opentherm
    ch_min_temperature:
      name: "Heating Minimum Temperature"
    ch_max_temperature:
      name: "Heating Maximum Temperature"
    dhw_min_temperature:
      name: "Hot Water Minimum Temperature"
    dhw_max_temperature:
      name: "Hot Water Maximum Temperature"
    pressure:
      name: "Heating Water Pressure"
    modulation:
      name: "Relative Modulation Level"
    boiler_temperature:
      name: "Boiler Temperature"
    return_temperature:
      name: "Return Temperature"
    room_temperature:
      name: "Room Temperature"
    room_setpoint_temperature:
      name: "Room Temperature Setpoint"

binary_sensor:
  - platform: opentherm
    ch_active:
      name: "Central Heating Active"
    dhw_active:
      name: "Hot Water Active"
    flame_active:
      name: "Flame"
    fault:
      name: "OEM Fault"
    diagnostic:
      name: "OEM Diagnostic"

switch:
  - platform: opentherm
    gateway_enabled:
      name: "Gateway Enabled"
    ch_enabled:
      name: "Central Heating Enabled"
    dhw_enabled:
      name: "Hot Water Enabled"

number:
  - platform: opentherm
    ch_setpoint_temperature:
      name: "Control Setpoint"
      min_value: 5.0
      max_value: 65.0
      step: 0.5
      restore_value: true
    dhw_setpoint_temperature:
      name: "Hot Water Setpoint"
      min_value: 40.0
      max_value: 65.0
      step: 0.5
      restore_value: true
    room_setpoint_temperature:
      name: "Room Temperature Setpoint"
      min_value: 5.0
      max_value: 25.0
      step: 0.5
      initial_value: 15.0
      restore_value: true

output:
  - platform: opentherm
    id: opentherm_output
